-- AlterTable
ALTER TABLE "ChargeRate" ALTER COLUMN "percentage" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "discount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PurchaseOrder" ALTER COLUMN "Paid" SET DATA TYPE DOUBLE PRECISION;
